# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  att_key: <%= ENV['DEAF_THERAPY_ATT_KEY'] %>
  att_secret: <%= ENV['DEAF_THERAPY_ATT_SECRET'] %>

development:
  <<: *default
  secret_key_base: e475a42b5cb12f3ecd93fc41c8bd0d6c6378863c04d4be9c6f402d4b08dc6bfd7a171848c30f1dfbd6d3f307265da12473292379cbdbdadec8ffbb1e31bade3e

test:
  <<: *default
  secret_key_base: aa2f3294f74f643750762b99326623d06d86362d4db59dff52ae8ef5158209145cca6ada33c53f311f413e7539e7b2362140f43cef468354a4aeb1d3ae0b14ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
